<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title>IPS Web Tracking/Item Tracking</title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
        <link href="st/css/ipswt.css" rel="stylesheet" type="text/css"/>
    </head>
    <body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td><img src="st/img/ipswebtrack.jpg" width="454" height="54"/></td>
                <td align="right" valign="middle"><a href="mailto:informatii@posta.md%20">Support</a>&nbsp;&nbsp;&nbsp;</td>
            </tr>
            <tr align="center">
                <td colspan="2">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><img src="st/img/sp.gif" name="iep" height="1" width="70" border="0"/></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <table width="65%" border="0" align="center" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td class="tabproperty">
                                            <table id="200" width="100%" border="0" cellspacing="1" cellpadding="3">
                                                <tr align="left" class="tabl2">
                                                    <td colspan="6"><strong>&nbsp;Identificarea :</strong></td>
                                                </tr>
                                                <tr align="left">
                                                    <td colspan="6" class="tabmen"><div align="left">Introduceti ID-ul trimiterii, apoi apasati Accept.</div></td>
                                                </tr>
                                                <tr class="tabl1">
                                                    <td colspan="6" align="center">
                                                        <form action="index.php" method="post">
                                                            <table width="100%" border="0" cellspacing="10" cellpadding="0">
                                                                <tr>
                                                                        <td>Trimiteri Id:</td><td><input name="itemid" type="text" id="itemid" size="30"/></td>
                                                                </tr>
                                                                <tr>
                                                                        <td>Auto track to email:</td>
                                                                            <td>
                                                                                <input name="email" type="text" id="email" size="30"/>
                                                                                &nbsp;&nbsp;&nbsp;
                                                                                <input type="submit" name="Submit" value="Accept"/>&nbsp;&nbsp;&nbsp; <input type="reset" name="Submit2" value="Anuleaza"/>
                                                                                &nbsp;&nbsp;&nbsp;
                                                                           </td>
                                                                </tr>
                                                            </table>
                                                        </form>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td width="18%"></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td width="18%"></td>
                                                    <td width="18%"></td>
                                                    <td width="18%"></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                    <table>
                        <tr>
                            <td>
                                <br/>
                                <br/>
                                [@DATA]
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <br/>
        <br/>
        <center>
            <hr width="50%" size="1" noshade/>
            2006 &copy; Postal Technology Centre
            <br/>
            <font size="1">www.ptc.upu.int</font>
            <br/>
        </center>
    </body>
</html>

